### PR TITLE
Token type vocab shape changed

### PR DESCRIPTION
**Pull request by Aktsvigun**
Hi mate,
found another small issue now, `convert_jax_checkpoint.py`, line 107:
instead of 
`'type_vocab_size': encoder['embedder']['type']['embedding'].shape[1]` 
we need
`'type_vocab_size': encoder['embedder']['type']['embedding'].shape[0]`

### CODE REVIEW

**Comment by erksch** [comment]
Oh yes, that's absolutely right.

**Comment by erksch** [comment]
Could you rebase your branch to the current master? There seems to be something off.

**Comment by Aktsvigun** [comment]
Done, it says there are no conflicts with the base branch (or am I missing something?)
Снимок экрана 2021-07-27 в 12 23 36

**Comment by erksch** [comment]
I can not merge due to conflicts. Also your fork states: "This branch is 5 commits ahead of erksch:master."

**Pull request closed without merging**
