### PR TITLE
Dropout in FNetLayer added

### PR DESCRIPTION
**Pull request by Aktsvigun**
Hi mate,

I guess you are missing the dropout layer inside FNetLayer. I've added it with `config['dropout_prob']` dropout value.

### CODE REVIEW

**Comment by erksch** [comment]
Good catch, here's the line in the official implementation for reference: https://github.com/google-research/google-research/blob/2b24b3710275ea38e603948bdbde6584c268f73e/f_net/layers.py#L82

**Comment by erksch** [comment]
The dropout prop used in the embeddings and in the feed forward layer is actually the same.

Embedding Dropout: https://github.com/google-research/google-research/blob/master/f_net/layers.py#L389

Feed Forward Dropout: https://github.com/google-research/google-research/blob/master/f_net/models.py#L71

both use the `dropout_rate` config. So we could also use the same value at both occasions.

**Comment by Aktsvigun** [comment]
Updated, changed dropout key for `dropout_rate`.

**Comment by erksch** [comment]
nice, please also update in the conversion file.
I will update the hosted checkpoint configs.

**Comment by Aktsvigun** [comment]
Sure, forgot about it. Guess it's done now.

**Comment by erksch** [comment]
Nice thank you for the help

**Pull request merged**
